/**
 * Anchor integration tests for paylix_payment_vault.
 *
 * Run with:
 *   cd packages/solana-program
 *   anchor test
 *
 * Requires: anchor-cli >= 0.30.1, solana-cli installed, a funded devnet or
 * localnet keypair at ~/.config/solana/id.json.
 *
 * NOTE: these tests expect the IDL + types to be generated via `anchor build`
 * before they run. The workspace declaration imports the program by name,
 * which anchor wires to the compiled artifact.
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import {
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAccount,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";

describe("paylix_payment_vault", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // @ts-expect-error — workspace name is generated by anchor build
  const program = anchor.workspace.PaylixPaymentVault as anchor.Program;

  let owner: Keypair;
  let platform: Keypair;
  let merchant: Keypair;
  let buyer: Keypair;
  let mint: PublicKey;
  let buyerAta: PublicKey;
  let merchantAta: PublicKey;
  let platformAta: PublicKey;

  const [vaultConfig] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault")],
    program.programId,
  );

  before(async () => {
    owner = (provider.wallet as anchor.Wallet).payer;
    platform = Keypair.generate();
    merchant = Keypair.generate();
    buyer = Keypair.generate();

    // Airdrop SOL to buyer so they can pay ATA creation + tx fees.
    const sig = await provider.connection.requestAirdrop(
      buyer.publicKey,
      1_000_000_000,
    );
    await provider.connection.confirmTransaction(sig, "confirmed");

    mint = await createMint(
      provider.connection,
      owner,
      owner.publicKey,
      null,
      6,
    );

    buyerAta = await createAssociatedTokenAccount(
      provider.connection,
      owner,
      mint,
      buyer.publicKey,
    );
    merchantAta = await createAssociatedTokenAccount(
      provider.connection,
      owner,
      mint,
      merchant.publicKey,
    );
    platformAta = await createAssociatedTokenAccount(
      provider.connection,
      owner,
      mint,
      platform.publicKey,
    );

    await mintTo(
      provider.connection,
      owner,
      mint,
      buyerAta,
      owner,
      1_000_000_000, // 1000 USDC equivalent
    );
  });

  it("initializes the vault config", async () => {
    await program.methods
      .initialize(platform.publicKey, 50)
      .accounts({
        config: vaultConfig,
        payer: owner.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    const cfg = await program.account.vaultConfig.fetch(vaultConfig);
    assert.strictEqual(cfg.platformFeeBps, 50);
    assert.strictEqual(cfg.paused, false);
  });

  it("adds the mint to the accepted-tokens list", async () => {
    const [accepted] = PublicKey.findProgramAddressSync(
      [Buffer.from("accepted"), mint.toBuffer()],
      program.programId,
    );
    await program.methods
      .setAcceptedToken(true)
      .accounts({
        config: vaultConfig,
        owner: owner.publicKey,
        mint,
        accepted,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    const row = await program.account.acceptedToken.fetch(accepted);
    assert.strictEqual(row.accepted, true);
  });

  it("creates a payment and splits the fee", async () => {
    const [accepted] = PublicKey.findProgramAddressSync(
      [Buffer.from("accepted"), mint.toBuffer()],
      program.programId,
    );
    const amount = new anchor.BN(100_000_000);
    const productId = Buffer.alloc(32, 1);
    const customerId = Buffer.alloc(32, 2);

    await program.methods
      .createPayment(amount, Array.from(productId), Array.from(customerId))
      .accounts({
        config: vaultConfig,
        mint,
        accepted,
        buyer: buyer.publicKey,
        buyerAta,
        merchantAta,
        platformAta,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    const merchantAcc = await getAccount(provider.connection, merchantAta);
    const platformAcc = await getAccount(provider.connection, platformAta);
    // 0.5% fee on 100 USDC = 0.5 USDC
    assert.strictEqual(Number(merchantAcc.amount), 99_500_000);
    assert.strictEqual(Number(platformAcc.amount), 500_000);
  });

  it("rejects payments with a non-accepted mint", async () => {
    const otherMint = await createMint(
      provider.connection,
      owner,
      owner.publicKey,
      null,
      6,
    );
    const [accepted] = PublicKey.findProgramAddressSync(
      [Buffer.from("accepted"), otherMint.toBuffer()],
      program.programId,
    );
    // accepted PDA for otherMint doesn't exist → account constraint fails
    let threw = false;
    try {
      await program.methods
        .createPayment(new anchor.BN(1_000), Array.from(Buffer.alloc(32)), Array.from(Buffer.alloc(32)))
        .accounts({
          config: vaultConfig,
          mint: otherMint,
          accepted,
          buyer: buyer.publicKey,
          buyerAta,
          merchantAta,
          platformAta,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
    } catch {
      threw = true;
    }
    assert.strictEqual(threw, true);
  });

  it("pause blocks payments, unpause re-enables them", async () => {
    await program.methods
      .pause()
      .accounts({ config: vaultConfig, owner: owner.publicKey })
      .rpc();
    let cfg = await program.account.vaultConfig.fetch(vaultConfig);
    assert.strictEqual(cfg.paused, true);

    await program.methods
      .unpause()
      .accounts({ config: vaultConfig, owner: owner.publicKey })
      .rpc();
    cfg = await program.account.vaultConfig.fetch(vaultConfig);
    assert.strictEqual(cfg.paused, false);
  });
});
